apiVersion: v1
kind: Service
metadata:
  name: whoami-np
spec:
  type: NodePort
  selector:
    app: whoami  
  ports:
    - port: 80           # port exposé à l'intérieur du cluster
      targetPort: 80     # port du container
      nodePort: 31000    # port accessible depuis l'extérieur du cluster

